### ISSUE TITLE
和原repo的精度有做过对比吗

### ISSUE THREAD

**Issue by chizhanyuefeng** [hsddlz/faster-CTPN#3]
这样做理论上，对于文本的前后语义关系应该没有lstm好。但是不知道你们的实验结果怎么样？

**Comment by hsddlz** [comment]
We have test the model on the ICDAR2013 and the conv1D with kernal size 3,5,7.
3 and 5 are less recall but 7 almost the same as the original.
in our private dateset kernal size 5 is best.

**Comment by chizhanyuefeng** [comment]
好的，十分感谢
