### ISSUE TITLE
关于速度

### ISSUE THREAD

**Issue by kasyoukin** [hsddlz/faster-CTPN#8]
我这边测试的速度并没有5倍提升那么夸张，大概只有10%
我用了 400张图片。
原版网络运行总时间112s
conv1d替换lstm运行总时间99s

**Comment by hsddlz** [comment]
training time on 10k images ,every images have at least 20 boxes.that's our environment. lstm training time 5days  but conv1d cost less than 1 day.

**Comment by kasyoukin** [comment]
哦，不好意思，少看了个training，我测试的是预测时间
